name: Python Due Date Calculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --exclude project/analytics/dds --show-source --statistics
        flake8 . --count --exit-zero --exclude project/analytics/dds --max-complexity=10 --max-line-length=200 --statistics
    - name: Coverage test with pytest
      run: |
        python3 -m pytest --exitfirst --verbose --failed-first --cov=project/